### ISSUE TITLE
A generic connector support

### ISSUE THREAD

**Issue by mmuru** [delta-io/connectors#43]
I would like to purpose an enhancement request to add a generic, open standard JDBC connector support for Delta lake tables so that any JDBC SQL clients and BI tools able to connect and explore the data. Also, the connector should provide a plugin like an interface that others can extend and add new connectors easily. The current Hive connector has limited support  and should support all hive engines since the delta lake connector is outside of Spark.

**Comment by zsxwing** [comment]
> I would like to purpose an enhancement request to add a generic, open standard JDBC connector support for Delta lake tables so that any JDBC SQL clients and BI tools able to connect and explore the data.

Delta Lake is a storage format. It's not an engine. The user needs to use an engine to read the table and do the computation. They should use the JDBC connector provided by the engine instead.

> Also, the connector should provide a plugin like an interface that others can extend and add new connectors easily. The current Hive connector has limited support and should support all hive engines since the delta lake connector is outside of Spark.

Do you mean a native reader to read Delta tables without Spark?

**Comment by mmuru** [comment]
Yes, a native reader to read Delta tables which supports JDBC/ODBC clients.

**Comment by zsxwing** [comment]
> supports JDBC/ODBC clients.

JDBC/ODBC means you need a computation system (Spark, Hive, Presto, Impala) to execute the SQL queries. Delta Lake is a storage format which cannot execute SQL queries. What we can do is building a native reader without using Spark so that it can be used to build connectors for computation systems (Hive, Presto, Impala) easily.

**Comment by mmuru** [comment]
I mean, build a native JDBC/ODBC reader using apache calcite to read Delta tables. Totally I understand Delta lake is a storage format but they are parquet files that can be read by Apache Drill or similar.

**Comment by zsxwing** [comment]
@mmuru IIUC, Apache Calcite is not an execution engine. Apache Drill is similar to Spark, Hive, Presto or Impala. We need to build a connector to make Apache Drill understand Delta Lake transaction logs. It looks like you are just asking for a connector that can be used in Apache Drill so that you can use its JDBC/ODBC connector to query a Delta Lake table in Apache Drill.

**Comment by schahaha** [comment]
Is there any native reader to read delta file ? If is ,any examples?   
I want to use my application to read and write detla file.

**Comment by dennyglee** [comment]
Hi @lecssmi - currently this connectors folder has the Delta Native Reader as well as the delta-rs repo as the Rust API per [Natively Query Your Delta Lake With Scala, Java, and Python](https://databricks.com/blog/2020/12/22/natively-query-your-delta-lake-with-scala-java-and-python.html). HTH!

**Comment by zsxwing** [comment]
@lecssmi We have released Delta Standalone Reader in 0.2.0.

Closing this ticket as we don't plan to build JDBC/ODBC connector which requires compute.
