### ISSUE TITLE
Flink Connector version 0.5.1-SNAPSHOT

### ISSUE THREAD

**Issue by ckavili** [delta-io/connectors#472]
Hi,

According to [flink connector documentation](https://github.com/delta-io/connectors/tree/master/flink) in the repo, there is. `0.5.1-SNAPSHOT` version of the connector working with Flink version `1.14.0 <= X <= 1.14.5`. When is it going to be released? Also, is flink version 1.14.5 really the most recent version that the connector supports or version v1.15+ will be also supported? I couldn't see this info on the roadmap.

Thank you 🌿

**Comment by kristoffSC** [comment]
Hi,
we recently migrated connector to 1.15.
https://github.com/delta-io/connectors/pull/434

This means that next release for connector will be supporting 1.15+ not 1.14.

However due to few Flink 1.15 bugs regarding Sink architecture
https://issues.apache.org/jira/browse/FLINK-29509
https://issues.apache.org/jira/browse/FLINK-29512
https://issues.apache.org/jira/browse/FLINK-29627

I would recommend to wait for Flink version 1.15.3 or 1.16.1 where all three above tickets will be included.

Flink 1.14 also seems to have some problems around that area but 1.14 is at the end of its life cycle, hence 1.15 migration.
https://issues.apache.org/jira/browse/FLINK-29589

Best Regards,
Krzysztof
