### ISSUE TITLE
[Feature Request] Flink Connector supports Update and Delete Delta Table

### ISSUE THREAD

**Issue by YannByron** [delta-io/connectors#479]
Hi guys, when can Flink-Connector support Update/Delete syntax.

**Comment by tdas** [comment]
Does Flink support DELETE/UPDATE SQL syntax? From their docs it does not seem so 
https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/overview/

**Comment by YannByron** [comment]
Not Flink SQL syntax.
I mean that use the  new-coming data to update/merge the existing table by flink-delta-connector, not just append. 
I don't know much about Flink. It may be impossible to do in current delta and flink env.

**Comment by scottsand-db** [comment]
Hi @YannByron - thanks for your question. Is UPDATE/DELETE possible using the DataStream API (since you clarified that you are not referring to the SQL API)?

We are currently working on SQL and catalog support for the Flink Sink and Source.

If you could help clarify some of your requirements for UPDATE/DELETE, and what sort of API you expect, that could help us plan what we work on after. Thanks!

**Comment by mberchon** [comment]
Hello,

I am not sure @YannByron was having the same in mind, but on my side I would have love the ability to use the delete / update and **upsert**  which is described from [delta doc](https://docs.delta.io/0.4.0/delta-update.html)

Let me extract a sample code with Spark:
```
import io.delta.tables._
import org.apache.spark.sql.functions._

val updatesDF = ...  // define the updates DataFrame[date, eventId, data]

DeltaTable.forPath(spark, "/data/events/")
  .as("events")
  .merge(
    updatesDF.as("updates"),
    "events.eventId = updates.eventId")
  .whenMatched
  .updateExpr(
    Map("data" -> "updates.data"))
  .whenNotMatched
  .insertExpr(
    Map(
      "date" -> "updates.date",
      "eventId" -> "updates.eventId",
      "data" -> "updates.data"))
  .execute()
```
